FROM python:3.7-buster

WORKDIR /app

COPY requirements.txt requirements.txt
COPY  mlflow-entrypoint.sh mlflow-entrypoint.sh

RUN apt update && apt install -y build-essential curl

RUN pip install -r requirements.txt

